#JPA /Hibernate Configuration
#Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/categorydb
spring.datasource.username=user
spring.datasource.password=user123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
config.value=You are in Dev environment