spring.application.name=category-servicee
server.port=9091
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#config client configuration,from where we need to read the value(currently reading from classpath)
spring.config.import=optional:configserver:http://localhost:9094


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=*


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


eureka.instance.hostname=localhost

spring.cloud.config.server.git.uri=https://github.com/prem27408/config-file
spring.cloud.config.server.git.default-label=main
#whenever application starts it should fetch
spring.cloud.config.server.git.clone-on-start=true
spring.profiles.active=dev

#rabbit mq configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


