spring.datasource.url=jdbc:postgresql://localhost:5432/categorydb
spring.datasource.username=root
spring.datasource.password=user123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
config.value=You are in Test environment