spring.application.name=config-server
server.port=9094

#Config server
#spring.cloud.config.server.native.search-locations=classpath:/config
#classpath
#spring.profiles.active=native

#config server:github
spring.cloud.config.server.git.uri=https://github.com/prem27408/config-file
spring.cloud.config.server.git.default-label=main
#whenever application starts it should fetch
spring.cloud.config.server.git.clone-on-start=true

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#by default these values are true
eureka.client.fetch.registry=true
eureka.client.register-with-eureka=true

